[workspace]
members = [
  "node",
  "runtime",
  "pallets/cairo",
  "pallets/starknet",
  "pallets/randomness",
  "primitives/starknet",
]
[profile.release]
panic = "unwind"

[workspace.package]
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
edition = "2021"
repository = "https://github.com/keep-starknet-strange/kaioshin/"


[workspace.dependencies]
# Substrate frame dependencies
frame-support = { default-features = false, git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
frame-benchmarking = { default-features = false, git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
frame-benchmarking-cli = { default-features = false, git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
frame-system = { default-features = false, git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
substrate-frame-rpc-system = { git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }

# Substrate pimitives dependencies
sp-core = { version = "7.0.0", default-features = false, git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sp-std = { default-features = false, git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sp-io = { default-features = false, git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sp-runtime = { version = "7.0.0", default-features = false, git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sp-consensus-aura = { git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sp-consensus = { version = "0.10.0-dev", git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sp-finality-grandpa = { git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sp-timestamp = { version = "4.0.0-dev", git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sp-inherents = { version = "4.0.0-dev", git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sp-keyring = { version = "7.0.0", git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sp-api = { version = "4.0.0-dev", git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sp-blockchain = { git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sp-block-builder = { git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }

# Substrate client dependencies
sc-network = { version = "0.10.0-dev", git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sc-network-common = { version = "0.10.0-dev", git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sc-consensus = { version = "0.10.0-dev", git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sc-finality-grandpa = { git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sc-rpc = { version = "4.0.0-dev", git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sc-rpc-api = { git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sc-basic-authorship = { git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sc-client-api = { git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sc-cli = { git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sc-executor = { git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sc-service = { git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sc-telemetry = { version = "4.0.0-dev", git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sc-keystore = { git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sc-transaction-pool = { version = "4.0.0-dev", git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sc-transaction-pool-api = { version = "4.0.0-dev", git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sc-consensus-aura = { git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }

# Substrate tools dependencies
substrate-build-script-utils = { git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }

# Substrate Frame pallet
pallet-transaction-payment = { default-features = false, git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
pallet-transaction-payment-rpc = { default-features = false, git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }

# Kaioshin pallets
pallet-cairo = { version = "0.1.0-dev", path = "pallets/cairo", default-features = false }
pallet-starknet = { version = "0.1.0-dev", path = "pallets/starknet", default-features = false }
pallet-kaioshin-randomness = { version = "0.1.0-dev", path = "pallets/randomness", default-features = false }

# Kaioshin primtitives
kp-starknet = { version = "0.1.0-dev", path = "primitives/starknet", default-features = false }

# Starknet dependencies
# Cairo Virtual Machine
# TODO: wait for no-std support on official repo
cairo-vm = { git = "https://github.com/open-dust/cairo-rs", branch = "wasm32-support", default-features = false, features = [
  "alloc",
] }
starknet-crypto = { git = "https://github.com/tdelabro/starknet-rs.git", branch = "feature/manual-no-std-bigdecimal", default-features = false }
starknet-ff = { git = "https://github.com/tdelabro/starknet-rs.git", branch = "feature/manual-no-std-bigdecimal", default-features = false }
poseidon_hash = { default-features = false, package = "poseidon", git = "https://github.com/EvolveArt/poseidon-rs", branch = "feature/no-std-refractor", features = [
  "alloc",
] }

# Other third party dependencies
lazy_static = { version = "1.4.0", default-features = false }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
  "derive",
] }
scale-info = { version = "2.1.1", default-features = false, features = [
  "derive",
] }
log = "0.4.17"
hex = { version = "0.4.3", default-features = false }
safe-mix = { version = "1.0", default-features = false }
jsonrpsee = { version = "0.16.2", default-features = false }
clap = { version = "4.0.9", default-features = false }
futures = { version = "0.3.21", default-features = false }

# patch generated by ./scripts/dev_manifest.sh
[patch."https://github.com/keep-starknet-strange/substrate"]
pallet-transaction-payment = { path = "../substrate/frame/transaction-payment" }
pallet-transaction-payment-rpc = { path = "../substrate/frame/transaction-payment/rpc" }
pallet-transaction-payment-rpc-runtime-api = { path = "../substrate/frame/transaction-payment/rpc/runtime-api" }
pallet-authorship = { path = "../substrate/frame/authorship" }
pallet-grandpa = { path = "../substrate/frame/grandpa" }
frame-system = { path = "../substrate/frame/system" }
frame-system-rpc-runtime-api = { path = "../substrate/frame/system/rpc/runtime-api" }
frame-support = { path = "../substrate/frame/support" }
frame-support-procedural = { path = "../substrate/frame/support/procedural" }
frame-support-procedural-tools = { path = "../substrate/frame/support/procedural/tools" }
frame-support-procedural-tools-derive = { path = "../substrate/frame/support/procedural/tools/derive" }
pallet-balances = { path = "../substrate/frame/balances" }
pallet-aura = { path = "../substrate/frame/aura" }
pallet-sudo = { path = "../substrate/frame/sudo" }
frame-benchmarking = { path = "../substrate/frame/benchmarking" }
frame-try-runtime = { path = "../substrate/frame/try-runtime" }
pallet-timestamp = { path = "../substrate/frame/timestamp" }
frame-executive = { path = "../substrate/frame/executive" }
pallet-session = { path = "../substrate/frame/session" }
substrate-wasm-builder = { path = "../substrate/utils/wasm-builder" }
fork-tree = { path = "../substrate/utils/fork-tree" }
substrate-build-script-utils = { path = "../substrate/utils/build-script-utils" }
frame-benchmarking-cli = { path = "../substrate/utils/frame/benchmarking-cli" }
substrate-frame-rpc-system = { path = "../substrate/utils/frame/rpc/system" }
substrate-prometheus-endpoint = { path = "../substrate/utils/prometheus" }
sp-database = { path = "../substrate/primitives/database" }
sp-runtime-interface = { path = "../substrate/primitives/runtime-interface" }
sp-runtime-interface-proc-macro = { path = "../substrate/primitives/runtime-interface/proc-macro" }
sp-consensus = { path = "../substrate/primitives/consensus/common" }
sp-consensus-aura = { path = "../substrate/primitives/consensus/aura" }
sp-consensus-slots = { path = "../substrate/primitives/consensus/slots" }
sp-tracing = { path = "../substrate/primitives/tracing" }
sp-maybe-compressed-blob = { path = "../substrate/primitives/maybe-compressed-blob" }
sp-core = { path = "../substrate/primitives/core" }
sp-core-hashing = { path = "../substrate/primitives/core/hashing" }
sp-core-hashing-proc-macro = { path = "../substrate/primitives/core/hashing/proc-macro" }
sp-state-machine = { path = "../substrate/primitives/state-machine" }
sp-keystore = { path = "../substrate/primitives/keystore" }
sp-weights = { path = "../substrate/primitives/weights" }
sp-io = { path = "../substrate/primitives/io" }
sp-runtime = { path = "../substrate/primitives/runtime" }
sp-inherents = { path = "../substrate/primitives/inherents" }
sp-transaction-pool = { path = "../substrate/primitives/transaction-pool" }
sp-std = { path = "../substrate/primitives/std" }
sp-finality-grandpa = { path = "../substrate/primitives/finality-grandpa" }
sp-storage = { path = "../substrate/primitives/storage" }
sp-panic-handler = { path = "../substrate/primitives/panic-handler" }
sp-debug-derive = { path = "../substrate/primitives/debug-derive" }
sp-blockchain = { path = "../substrate/primitives/blockchain" }
sp-externalities = { path = "../substrate/primitives/externalities" }
sp-trie = { path = "../substrate/primitives/trie" }
sp-version = { path = "../substrate/primitives/version" }
sp-version-proc-macro = { path = "../substrate/primitives/version/proc-macro" }
sp-block-builder = { path = "../substrate/primitives/block-builder" }
sp-keyring = { path = "../substrate/primitives/keyring" }
sp-staking = { path = "../substrate/primitives/staking" }
sp-wasm-interface = { path = "../substrate/primitives/wasm-interface" }
sp-transaction-storage-proof = { path = "../substrate/primitives/transaction-storage-proof" }
sp-arithmetic = { path = "../substrate/primitives/arithmetic" }
sp-api = { path = "../substrate/primitives/api" }
sp-api-proc-macro = { path = "../substrate/primitives/api/proc-macro" }
sp-offchain = { path = "../substrate/primitives/offchain" }
sp-timestamp = { path = "../substrate/primitives/timestamp" }
sp-application-crypto = { path = "../substrate/primitives/application-crypto" }
sp-rpc = { path = "../substrate/primitives/rpc" }
sp-session = { path = "../substrate/primitives/session" }
sc-consensus = { path = "../substrate/client/consensus/common" }
sc-consensus-aura = { path = "../substrate/client/consensus/aura" }
sc-consensus-slots = { path = "../substrate/client/consensus/slots" }
sc-tracing = { path = "../substrate/client/tracing" }
sc-tracing-proc-macro = { path = "../substrate/client/tracing/proc-macro" }
sc-rpc-spec-v2 = { path = "../substrate/client/rpc-spec-v2" }
sc-state-db = { path = "../substrate/client/state-db" }
sc-proposer-metrics = { path = "../substrate/client/proposer-metrics" }
sc-keystore = { path = "../substrate/client/keystore" }
sc-peerset = { path = "../substrate/client/peerset" }
sc-rpc-server = { path = "../substrate/client/rpc-servers" }
sc-network = { path = "../substrate/client/network" }
sc-network-bitswap = { path = "../substrate/client/network/bitswap" }
sc-network-transactions = { path = "../substrate/client/network/transactions" }
sc-network-common = { path = "../substrate/client/network/common" }
sc-network-light = { path = "../substrate/client/network/light" }
sc-network-sync = { path = "../substrate/client/network/sync" }
sc-informant = { path = "../substrate/client/informant" }
sc-transaction-pool = { path = "../substrate/client/transaction-pool" }
sc-transaction-pool-api = { path = "../substrate/client/transaction-pool/api" }
sc-utils = { path = "../substrate/client/utils" }
sc-cli = { path = "../substrate/client/cli" }
sc-chain-spec = { path = "../substrate/client/chain-spec" }
sc-chain-spec-derive = { path = "../substrate/client/chain-spec/derive" }
sc-finality-grandpa = { path = "../substrate/client/finality-grandpa" }
sc-basic-authorship = { path = "../substrate/client/basic-authorship" }
sc-storage-monitor = { path = "../substrate/client/storage-monitor" }
sc-block-builder = { path = "../substrate/client/block-builder" }
sc-allocator = { path = "../substrate/client/allocator" }
sc-network-gossip = { path = "../substrate/client/network-gossip" }
sc-client-db = { path = "../substrate/client/db" }
sc-client-api = { path = "../substrate/client/api" }
sc-sysinfo = { path = "../substrate/client/sysinfo" }
sc-executor = { path = "../substrate/client/executor" }
sc-executor-wasmtime = { path = "../substrate/client/executor/wasmtime" }
sc-executor-wasmi = { path = "../substrate/client/executor/wasmi" }
sc-executor-common = { path = "../substrate/client/executor/common" }
sc-telemetry = { path = "../substrate/client/telemetry" }
sc-offchain = { path = "../substrate/client/offchain" }
sc-service = { path = "../substrate/client/service" }
sc-rpc = { path = "../substrate/client/rpc" }
sc-rpc-api = { path = "../substrate/client/rpc-api" }
