---
blank_issues_enabled: false
contact_links:
  - name: Kaioshin Community Support
    url: https://github.com/keep-starknet-strange/kaioshin/discussions
    about: Please ask and answer questions here.
